name: BeES Tracker

on:
  schedule:
    - cron: "0 4-9 * * 1-5"   # Runs hourly 04:00–09:00 UTC (Mon–Fri)
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install yfinance pandas pytz
          
      - name: Debug tree
        run: |
          pwd
          ls -la

      - name: Run tracker
        run: python etf_2.py

        
      - name: Commit result file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add result.txt
          git commit -m "Update ETF result" || echo "No changes"
          git push


