name: ETF Tracker Pages

on:
  schedule:
    - cron: "*/60 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-etf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install yfinance pandas pytz

      - name: Run ETF tracker
        run: python etf_2.py

      - name: Debug output
        run: ls -l output

      - name: Publish output to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./output
          force_orphan: true
